version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory to /app in the container for live reload
    environment:
      - REDIS_URL=redis://redis:6379  # If you're using Redis, adjust this accordingly
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
